# Generated by Django 5.2 on 2025-05-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Misc', 'Miscellaneous'), ('Clothing', 'Clothing'), ('Toiletries', 'Toiletries'), ('Electronics', 'Electronics'), ('Accessories', 'Accessories'), ('Documents', 'Documents'), ('Food', 'Food'), ('Health', 'Health'), ('Gear', 'Gear'), ('Baby/Kids', 'Baby/Kids'), ('Beach/Pool', 'Beach/Pool'), ('Work', 'Work'), ('Entertainment', 'Entertainment'), ('Camping', 'Camping'), ('Winter Gear', 'Winter Gear'), ('Fitness', 'Fitness')], default='Misc', max_length=30, verbose_name='Category')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Trip Name')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('packing_items', models.ManyToManyField(blank=True, to='travel.packingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Itinerary date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('type', models.CharField(choices=[('X', 'Other'), ('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('A', 'Activity'), ('T', 'Travel'), ('C', 'Check-in'), ('O', 'Check-out'), ('E', 'Event'), ('F', 'Free Time'), ('M', 'Meeting')], default='X', max_length=1, verbose_name='Itinerary Type')),
                ('activity', models.CharField(max_length=255, verbose_name='Activity')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.trip')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
